name: IoT Streaming CD

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:

  deploy:
    name: Dataflow Deployment
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/391196644919/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: iot-cicd-deployer@iot-gcp-streaming.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Verify Google Cloud identity
        run: |
          gcloud auth list
          gcloud config set project iot-gcp-streaming
          gcloud projects describe iot-gcp-streaming --format="value(projectId)"

      - name: Verify Dataflow access
        run: |
          gcloud dataflow jobs list \
            --region=asia-south1 \
            --project=iot-gcp-streaming